# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - azure-devops
          - kusto-server
          - pdf-tools
          - api-tools
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm install
        working-directory: ${{ matrix.package }}
      - run: npm run build
        working-directory: ${{ matrix.package }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - azure-devops
          - kusto-server
          - pdf-tools
          - api-tools
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: https://registry.npmjs.org/
      - run: npm install
        working-directory: ${{ matrix.package }}
      - name: Set package version from GitHub release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          npm version --no-git-tag-version "$VERSION"
        working-directory: ${{ matrix.package }}
      - run: npm publish
        working-directory: ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
